app:
  security:
    jwt:
      access-secret: ${ACCESS_SECRET}
      access-expiration: ${ACCESS_EXPIRATION}
      refresh-secret: ${REFRESH_SECRET}
      refresh-expiration: ${REFRESH_EXPIRATION}
server:
  port: ${SERVER_PORT}
spring:
  application:
    name: quikz-backend
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    driver-class-name: ${DATABASE_DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.authentication: DEBUG

